### ISSUE TITLE
Error: 'browser' must be a non-empty character string

### ISSUE THREAD

**Issue by PedroRaposo** [anders-biostat/sleepwalk#10]
Hello,

After calling the sleepwalk function on a Seurat object, I got this error:

```
> sleepwalk( as.matrix(BAM@reductions$umap@cell.embeddings), as.matrix(BAM@reductions$pca@cell.embeddings) )

Estimating 'maxdist' for feature matrix 1
Error in browseURL(str_c("http://localhost:", port, "/", pageobj$startPage),  :
  'browser' must be a non-empty character string
```

I have loaded the stringr library (containing the function `str_c()`), and I cannot find the file originating this error. Can I ask if someone had this problem at some point?

Thank you

**Comment by kloivenn** [comment]
Hello Pedro,

Unfortunately, I can't reproduce your error on my laptop. 
Could you, please, tell where are you trying to run sleepwalk? What is the operating system? Are you using RStudio or not? May be you could also add output of `sessionInfo()`?

The error originates in `jrc::openPage` function or, more specifically, in `utils::browseURL`. It seems that the problem is in finding your default web browser. You can try to overcome it by selecting a browser manually (add `browser = "path/to/your/browser/"`) to sleepwalk call.

Best regards,
Sveta.

**Comment by PedroRaposo** [comment]
Hello @kloivenn.
Thank you for your fast response. You're right, that was the issue.
After I set things up, I'm faced with a blank html page, but I guess I'll have to go to another thread  (#3).
Thank you
