### ISSUE TITLE
Error running sleepwalk: cannot open the connection

### ISSUE THREAD

**Issue by gufranca** [anders-biostat/sleepwalk#11]
Dear sleepwalk developers,
Thanks a lot for providing such nice method. I could install the package but I get the following error when I tried to run:

```
> sleepwalk(myseuratobj@dr$umap@cell.embeddings, myseuratobj@dr$pca@cell.embeddings)
Estimating 'maxdist' for feature matrix 1
Server has been stopped.
Server has been stopped.
Error in app$openPage(useViewer, browser) : 
  Timeout waiting for websocket.
In addition: Warning messages:
1: In file(con, "r") :
  cannot open file 'sleepwalk_canvas.html': No such file or directory
2: In func(req) : File '/favicon.ico' is not found
```
I know this is probably not a sleepwalk specific error, but I couldn't find a solution for this. Any hints/help on how to fix this issue?

Also, I have a question about the output. Besides using the interactive mode to manually inspect cells that might be "misplaced" on the reduced-dimension space, I would like to systematically find the cells that don't quite fit to the clusters they were originally assigned to. In other words, how would you suggest to use sleepwalk to refine my clustering since I suspect that many of my cells were wrongly assigned to their clusters. I am using Seurat package to reduce dimension and clustering.

Thank you very much,
Gustavo

**Comment by kloivenn** [comment]
Hi Gustavo,

The problem was actually in sleepwalk. I've fixed it and right now submitting a fixed version to CRAN since it is quite critical. However, for a new version to appear on CRAN may take some time, so you can reinstall sleepwalk from github.

As for your question, sleepwalk designed as a purely exploratory tool. It may alert you to the presence of abnormalities in your clustering and also can help you to specify the suspicious region (you can select some points by holding your mouse button and then access indices of selected points with the `on_selection` argument). However, a proper systematic analysis is a different question, that can be very specific to your data and your research.

In general, sleepwalk can be used to confirm presence of such an effect (presence of cells that are too far from others in the same cluster), highlight suspicious cells and to get a rough idea of the scale of the effect (what is the usual distance within a cluster and how far are possibly misassigned cells). 

After that one can use this information for further analysis such as calculating distances within the cluster or to closest members of the cluster and checking for the outliers or checking if the suspicious cells express something they shouldn't. But in any case, the next steps very much depends on what you expect your cluster to be and what make you think that some cells should not be assigned to it.
 
Sorry for the vague answer, but it is a really complex question with lots of things to consider.

Best regards,
Svetlana

**Comment by gufranca** [comment]
Hi Svetlana,
Thank you so much for your quick and detailed reply! I will reinstall it from github.
Thanks also for providing an explanation for my question. I know it's a tricky one and there is no automatic way to figure that out. I think sleepwalk can be helpful to accomplish the task of identifying mislabeled cells. I will look into that in more detail. 
Best wishes,
Gustavo
