### ISSUE TITLE
empty web output

### ISSUE THREAD

**Issue by staracode** [anders-biostat/sleepwalk#3]
Any idea why this output is empty.  Tried to look inside the function with debug(sleepwalk) and everything looks ok.  
<img width="561" alt="screen shot 2019-01-08 at 7 50 02 pm" src="https://user-images.githubusercontent.com/15679734/50875815-e62c9800-137e-11e9-8636-845a6ab74ae3.png">

**Comment by simon-anders** [comment]
Can you give us a bit more information, please?
- What command were you running in R?
- Maybe give us the structure (with `str`) for the matrices that you have passed
- If you look into the Javascript Console ("Tools" menu in Chrome;  Tools / Web Developer / Web Console for Firefox), can you see any error messages?

Thanks.

**Comment by kloivenn** [comment]
May be you've used data.frame as input? If so, the issue is probably solved here #1

**Comment by staracode** [comment]
Yes, converting to matrix using as.matrix solves the problem!  

I had an error converting the embedding variable to a matrix last night (something about an S4 object that couldn't be converted) and assumed keeping it as a data.frame would be fine since it didn't throw any errors and looked fine when debugging.  But the conversion somehow works today after clearing my history and re-running everything.   

sleepwalk(as.matrix(singlecelldataset@dr[["tsne"]]@cell.embeddings), featureMatrices = as.matrix(t(singlecelldataset@data)))

Thanks for creating this visualization!

Thanks, 
Tara

<img width="515" alt="screen shot 2019-01-09 at 10 53 42 am" src="https://user-images.githubusercontent.com/15679734/50921861-de600880-13fd-11e9-848f-54de1b2105a0.png">

**Comment by staracode** [comment]
Yes, converting to matrix using as.matrix solves the problem!


I had an error converting the embedding variable to a matrix last night (something about an S4 object that couldn't be converted) and assumed keeping it as a data.frame would be fine since it didn't throw any errors and looked fine when debugging.  But the conversion somehow works today after clearing my history and re-running everything.


sleepwalk(as.matrix(singlecelldataset@dr[["tsne"]]@cell.embeddings), featureMatrices = as.matrix(t(singlecelldataset@data)))


Thanks for creating this visualization!


Thanks,

Tara

________________________________

**Comment by PedroRaposo** [comment]
Hello,
I'm having similar issues. As @simon-anders suggested, here is the information that I got:
- Here's the code I run: `sleepwalk(as.matrix(BAM_small$umap@cell.embeddings), as.matrix(BAM_small$pca@cell.embeddings))`
- Here's the structure of the objects: 

```

 > str(BAM_small$umap@cell.embeddings)
  num [1:100, 1:2] 1.42 1.6 2.75 2.27 1.62 ...
  - attr(*, "scaled:center")= num [1:2] 2.15 3.5
  - attr(*, "dimnames")=List of 2
   ..$ : chr [1:100] "TACTTACGTCCTCATC_1" "ATTACCTTCCGTACGG_1" "TCAGCCTGTGCTCTTC_1" "GTGGGAACAATACGAA_1" ...
   ..$ : chr [1:2] "UMAP_1" "UMAP_2" 

> str(BAM_small$pca@cell.embeddings)
 num [1:100, 1:50] -16.06 -18.9 -16.42 -13.17 -9.06 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:100] "TACTTACGTCCTCATC_1" "ATTACCTTCCGTACGG_1" "TCAGCCTGTGCTCTTC_1" "GTGGGAACAATACGAA_1" ...
  ..$ : chr [1:50] "PC_1" "PC_2" "PC_3" "PC_4" ...
```
- And here's the error that showed in my browser's Javascript Console:
![image](https://user-images.githubusercontent.com/16338197/71081960-26e48200-2188-11ea-8889-b917c9acb95b.png)

I have looked into the error in question, but I couldn't figure out what the actual problem was:
![image](https://user-images.githubusercontent.com/16338197/71082125-7dea5700-2188-11ea-8646-50bdbf5f5bed.png)

Does anyone has any ideas what it could be?
Thank you in advance

**Comment by simon-anders** [comment]
Hi Pedro

thanks for digging into this. At the point of the error that you indicated, Sveta has used `=>`, the new JavaScript arrow notation for anonymous function, which is not supported by older browsers.

What browser and version do you use? See here for a table with minimal versions: https://caniuse.com/#feat=arrow-functions

@kloivenn:  I've avoided using arrow function so far due to lack of support. On the other hand, it's supported by most browsers since 2016, and soon it'll be 2020.

  Simon

**Comment by PedroRaposo** [comment]
Hi Simon,
You're absolutely right. I verified and this notation was incompatible with my current browser.
After changing to a compatible browser (referenced in #10 by @kloivenn), it worked right away!

Thank you very much!
